# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82f9b6e1cee2a34f37b2015ed82ba353e007a62d42d6a1dfd5659d3532d56a3f9c543193f1ab3d8ce3f944dceb34c3af0c24f0934924dce632bd04bfda8b7458

test:
  secret_key_base: ea4e54c6d1789058dd6f50e1d01e2a11e1bd99b40e155d2c4768b5e3e114490c71c738828523542b6804730f990682f266c3b20c612fdbfa7042ea94db7b4ac4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
